version: '3'
services:
  pes:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: pes
    image: pes
    ports:
      - "3000:3000"
    volumes:
      - "./off-home.sqlite3:/app/off-home.sqlite3"
      - "./off-home-93451-firebase-adminsdk-ew1oq-42cac07c20.json:/app/off-home-93451-firebase-adminsdk-ew1oq-42cac07c20.json"
      - "./images:/app/images"
    restart: unless-stopped
